### ISSUE TITLE
run.sh

### ISSUE THREAD

**Issue by elRadix** [rockneurotiko/go-bots#2]
I have issue running that on a debian box

error message
/bin/rssbot_linux_386: 5: /bin/rssbot_linux_386: Syntax error: newline unexpected\

my run.sh
# !/usr/bin/env bash

BINARY=/bin/rssbot_linux_386
DBPATH=/opt/go-bots/rssbot/db/rss.db
ENVDIR=/opt/go-bots/rssbot/secrets.env
URL=""

$BINARY --db $DBPATH --env $ENVDIR --deploy=$URL

**Comment by rockneurotiko** [comment]
And `/bin/rssbot_linux_386` is the binary from `go-bot-binaries`?

**Comment by elRadix** [comment]
yes downloaded from go-bot-binaries, same error for the amd64 version

/bin/rssbot_linux_amd64: 5: /bin/rssbot_linux_amd64: Syntax error: newline unexpected

root@xxxx:/opt/go-bots/rssbot# rssbot_linux_amd64
/bin/rssbot_linux_amd64: line 4: syntax error near unexpected token `newline'
/bin/rssbot_linux_amd64: line 4:`<!DOCTYPE html>'

**Comment by rockneurotiko** [comment]
Hmmmmm, that's strange, I can execute the binary from that project.
Are you sure that you are executing it righ? (right click in RAW and save link as, or cloning the project)
Try with a relative path instead than a absolute, but I'm using an absolute right now.
Also, try executing the binary directly.
If all that fails, you can try to build the main.go yourself (`go build main.go`)

**Comment by elRadix** [comment]
its working now, cloned the whole binary folder locally, maybe something went wrong downloading the single binary.

next question, how can i run it as daemon ?

**Comment by rockneurotiko** [comment]
That depend of your operating system and if it uses upstart or systemd or another one.
You have an example of configuration file to upstart in [the bookbot](https://github.com/rockneurotiko/go-bots/blob/master/bookbot/etc/bookbot.conf)
