### ISSUE TITLE
webhook error

### ISSUE THREAD

**Issue by elRadix** [rockneurotiko/go-bots#3]
i see many error messages filling up my logs like these:
logger: Some error happened in your petition, check your token or remove the webhook.

what does is it mean, how to fix it ?

**Comment by rockneurotiko** [comment]
You are not using webhook, so the problem is in the token :smile: 
Probably the `secrets.env` file is bad, it have to be like:

```
TELEGRAM_TOKEN=1111111:AAAAAAAABBBBBBBBBBB
```

**Comment by elRadix** [comment]
thank you!
