### ISSUE TITLE
RSS xml error

### ISSUE THREAD

**Issue by elRadix** [rockneurotiko/go-bots#4]
Is there way this fix this error message ?

/sub http://tweakers.net/feeds/mixed.xml
Bad RSS: http://tweakers.net/feeds/mixed.xml, maybe the URL is bad.
Error msg: XML syntax error on line 2: invalid UTF-8

**Comment by bhzdcz** [comment]
how can I set /new command to fetch latest rss item?

**Comment by rockneurotiko** [comment]
@elRadix that error is not because of my project, that error is throwed by [https://github.com/jteeuwen/go-pkg-rss](https://github.com/jteeuwen/go-pkg-rss), the library I use for the RSS fetch and decode.

@3ehzad open an issue for that kind of things, but the answer is easy, program it :smile:
